### PR TITLE
Change license to MIT

### PR DESCRIPTION
**Pull request by ralphlange**
Set the nds-adq module to use the same MIT license as the other two nds-modules under this org.
Also move license file to project root.

### CODE REVIEW

**Comment by dsoklic** [comment]
@ralphlange wasn't here the problem that Teledyne holds the copyright?

**Comment by ralphlange** [comment]
If so, why is there a Cosylab license?

**Comment by ralphlange** [comment]
@TSPD-Support - please help!

If we all agree that this should be done, this PR could be merged, right?

**Comment by TSPD-Support** [comment]
> @TSPD-Support - please help!
> 
> If we all agree that this should be done, this PR could be merged, right?

Yes, we all agree that MIT is good for this.

**Review by TSPD-Support — APPROVED** [review]
OK

**Pull request merged**
